### ISSUE TITLE
Hull White Market Consistency

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/EconomicScenarioGenerators.jl#28]
Why is this test broken? @kasperrisager I could use your expertise again 🤔 

The test is intended to check that we can re-create a market price using the observed input curve. 

This is the last issue to resolve before announcing the package as a technical preview more widely.

**Comment by kasperrisager** [comment]
I did a bit of fiddling around with it - I didn't get to a conclusion, but I have some observations:
* Running with a sigma of zero also breaks the test, so we're probably looking at the theta function
* ... unless it's a discretization issue, but I think it looks too big for that.
* Breaking gets worse and worse the further out on the curve we get.
* I was actually surprised that any of this worked given that the function definition in src/Yields.jl is off (variable sg doesn't match input parameter which is s)
I'll continue looking...

**Comment by alecloudenback** [comment]
Thanks for starting to look at this. What do you mean by: 
> I was actually surprised that any of this worked given that the function definition in src/Yields.jl is off (variable sg doesn't match input parameter which is s)

**Comment by alecloudenback** [comment]
Ah, I see what you mean. It was falling back to the default (the SG is an iterable which Yields iterates and assumes the timepoints are 1:n instead of whatever the SG timepoints actually are. This is fixed in 648ce0d149e1fcc56d36b68c0abf45bd50cde7f7.

Still not resolved, I'm going to start a branch with some work on it though.

**Comment by alecloudenback** [comment]
So some additional observations:

- When using `Yields.Constant` as the observed curve, the `pv` matches the deterministic case, so something to do with the shape of the curve?
- When setting the HullWhite `σ` to be zero the replication is still off (so not due to the diffusion part of the process?).
- The `a` parameter also doesn't seem to be significant in achieving convergence

**Comment by alecloudenback** [comment]
Here's a script I'm using to investigate. It appears that the smaller the timesteps, the flatter the generated curves become:

```julia
using Yields, EconomicScenarioGenerators
using Plots

rates =[0.01, 0.01, 0.03, 0.05, 0.07, 0.16, 0.35, 0.92, 1.40, 1.74, 2.31, 2.41] ./ 100
mats = [1/12, 2/12, 3/12, 6/12, 1, 2, 3, 5, 7, 10, 20, 30]
c = Yields.CMT(rates,mats)

function show_scens(curve,timestep)
    m = HullWhite(.1,.000,c) # a, σ, curve

    s = ScenarioGenerator(
            timestep,  # timestep
            30., # projection horizon
            m,  # model
        )

    n = 1000
    curves = [Yields.Forward(s) for i in 1:n]

    let
        times = 0.5:0.1:30
        p=plot(title="timestep: $timestep")
        for d in curves
            plot!(p,times,Yields.rate.(Yields.zero.(d,times)),alpha=0.2,label="")
        end

        plot!(times,Yields.rate.(Yields.zero.(c,times)),line=( :black, 5,0.5), label="Given Yield Curve")
        p
    end
end
anim = @animate for ts in [0.1,0.25,0.5,1.,1.5,2.]
    show_scens(c,ts)
end

gif(anim,fps=1.5)
```

![plot_14](https://user-images.githubusercontent.com/711879/181920131-74f19022-7c3d-43ab-b2e5-065f0268c8f1.gif)

**Comment by alecloudenback** [comment]
Ok, after noticing that there was a `δT` in the denominator of one of the `θ` terms in the [StackOverflow reference](https://quant.stackexchange.com/a/8734/30382), I [updated](https://github.com/JuliaActuary/EconomicScenarioGenerators.jl/pull/32/commits/8d2b596bf16774285b088e913a4d714ac4a0e64f) to divide by `timestep` and the fit is better overall but still not resolved:
![plot_17](https://user-images.githubusercontent.com/711879/181920634-639287fa-70e2-43ea-b9fa-e37c40afd6c8.gif)

**Comment by alecloudenback** [comment]
I'm also experimenting with defining:

```julia
f(t) = Yields.discount(M.curve,t[1])
δf = -only(ForwardDiff.hessian(f,[time]))
f_t = -only(ForwardDiff.gradient(f,[time]))
```

based on the definition in [this paper](https://mdpi-res.com/d_attachment/mathematics/mathematics-08-01719/article_deploy/mathematics-08-01719-v2.pdf?version=1603181408) (page 3) but still not getting good results

**Comment by alecloudenback** [comment]
I think I've figured it out, let me test a few more things though :)
![plot_46](https://user-images.githubusercontent.com/711879/182008213-56c2569d-15c2-4e16-9be4-5473691953f6.gif)

**Comment by alecloudenback** [comment]
So the issue was with my understanding primarily, not being very familiar with ESGs and all. The values coming out of the interest rate process aren't the forward rates from time t to t+timestep, it's the change in the discount factor. Now in the Yields.jl file within ESG.jl, there is a function to accumulate the discount factor. This can encounter cases where the discount factor becomes negative and then it errors when creating a yield curve - see #33 

Does that make sense where I went wrong and what the fix was? My sense is that it could be made better to avoid the issue in #33.  The key change is the changes to the Yields.jl file.

**Comment by kasperrisager** [comment]
I'm happy to see it work 😄, and I guess the problem all along was just to get a good representation of theta. The current one is mathematically clear, but I think it has an equivalent form in terms of the instantaneous forward rate and its time derivative (all measured on the initial curve) and maybe there could be functions for these in package `Yields.jl` (or maybe it's actually better to just do the auto diff instead of expecting underlying packages to expose derivatives 🤔 ?).

**Comment by kasperrisager** [comment]
And as you write, the process is not for a forward rate but for an actual short rate which is realized. The result comes out as a yield curve which, I guess, is mathematically fine, and gives access to e.g. `pv` methods that are the discount factors for the scenario. But I must admit I was a little surprised, since I'd normally use yield curves to represent something happening in the future of the scenario, and not on its past path. Again, mathematically fine, which, in my book, makes it fine, generally.
